### ISSUE TITLE
Does this implement exponential back-off?

### ISSUE THREAD

**Issue by raghavdelhi** [jacobp100/node-gcm-ccs#18]
Not really an issue, but a question. Does the library implement exponential back-off? https://developers.google.com/api-client-library/java/google-http-java-client/backoff

I see that you have implemented queues. Is the exponential back-off built into those?

**Comment by jacobp100** [comment]
Probably not! I wrote this a long time and remember none of it. Sorry I can't be of more help.

**Comment by raghavdelhi** [comment]
Yeah, reviewed the code, it doesn't seem so. Thanks a lot though, its a great starting point to build a node js xmpp connection server!
